# Generated by Django 4.1.7 on 2023-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_employeefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
