# Generated by Django 4.1.7 on 2023-10-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_document_created_by_document_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_email_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
