# Generated by Django 4.1.7 on 2023-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_document_is_email_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='matricule',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeFile',
        ),
    ]
