# Generated by Django 4.1.7 on 2023-10-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_employee_matricule_delete_employeefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_whatsapp_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='position_salary',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
