# Generated by Django 4.1.7 on 2024-06-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='scraped_data',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='acheteur_public',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='categorie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='date_limite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='lieu_execution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='objet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='procedure',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='publie_le',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
