# Generated by Django 4.1.7 on 2024-06-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_remove_scrapeddata_scraped_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='reference_hash',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='categorie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='date_limite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='procedure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='publie_le',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reference',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
