# Generated by Django 4.1.7 on 2024-06-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_scrapeddata_reference_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='org',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
