# Generated by Django 4.1.7 on 2024-06-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_scrapeddata_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='date_limite',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='adresse_depot_offres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='adresse_retrait_dossiers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='agrements',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='caution_provisoire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='contact_administratif',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='lieu_ouverture_plis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='prix_acquisition_plans',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='prospectus_notices',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='qualifications',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='reunion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='variante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='visites_lieux',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='categorie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='org',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='procedure',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='publie_le',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reference_hash',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
