# Generated by Django 4.1.7 on 2024-06-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_remove_scrapeddata_date_limite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='prospectus_notices',
            new_name='domaines_activite',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='date_limite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='estimation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='prospectus_notices_documents',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='reserve_tpe_pme',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='adresse_depot_offres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='adresse_retrait_dossiers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='agrements',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='categorie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='caution_provisoire',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='org',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='prix_acquisition_plans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='procedure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='publie_le',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='qualifications',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reference_hash',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reunion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='variante',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='visites_lieux',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
