# Generated by Django 4.1.7 on 2024-06-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_rename_prospectus_notices_scrapeddata_domaines_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='estimation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
