# Generated by Django 4.1.7 on 2024-06-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_alter_scrapeddata_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='adresse_depot_offres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='adresse_retrait_dossiers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='agrements',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='caution_provisoire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='contact_administratif',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='domaines_activite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='lieu_ouverture_plis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='prix_acquisition_plans',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='prospectus_notices_documents',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='qualifications',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reserve_tpe_pme',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reunion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='variante',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='visites_lieux',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
