# Generated by Django 4.1.7 on 2024-06-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0008_alter_scrapeddata_adresse_depot_offres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='json_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
