# Generated by Django 4.1.7 on 2024-06-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0009_scrapeddata_json_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='SectorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='scrape.sector')),
            ],
            options={
                'verbose_name': 'Sector Category',
                'verbose_name_plural': 'Sector Categories',
                'unique_together': {('sector', 'name')},
            },
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='scraped_data', to='scrape.sectorcategory'),
        ),
    ]
