# Generated by Django 4.1.7 on 2024-06-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0010_sector_sectorcategory_scrapeddata_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrape.sector'),
        ),
    ]
