# Generated by Django 4.1.7 on 2024-06-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0011_alter_scrapeddata_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
