# Generated by Django 4.1.7 on 2024-06-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0012_alter_scrapeddata_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='procedure',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='procedure',
            field=models.ManyToManyField(blank=True, to='scrape.procedurechoice'),
        ),
    ]
