# Generated by Django 4.1.7 on 2024-06-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0013_procedurechoice_remove_scrapeddata_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
