# Generated by Django 4.1.7 on 2024-06-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0014_alter_scrapeddata_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='publie_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
