# Generated by Django 4.1.7 on 2024-06-29 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0015_alter_scrapeddata_publie_le'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='domaines_activite',
        ),
        migrations.AlterField(
            model_name='sectorcategory',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='scrape.sector'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='domaines_activite',
            field=models.ManyToManyField(blank=True, to='scrape.sectorcategory'),
        ),
    ]
