# Generated by Django 4.1.7 on 2024-06-29 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0016_remove_scrapeddata_domaines_activite_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectorcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sectorcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.sectorcategory'),
        ),
        migrations.RemoveField(
            model_name='sectorcategory',
            name='sector',
        ),
    ]
